# Generated by Django 4.1 on 2022-09-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1000, null=True)),
                ('address', models.TextField(max_length=200)),
                ('is_published', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
